[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security Headers
[[headers]]
  for = "/*"
  [headers.values]
    # Prevent XSS attacks
    X-XSS-Protection = "1; mode=block"
    
    # Prevent clickjacking
    X-Frame-Options = "DENY"
    
    # Prevent MIME type sniffing
    X-Content-Type-Options = "nosniff"
    
    # Referrer Policy
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # Permissions Policy
    Permissions-Policy = "camera=(), microphone=(), geolocation=(), interest-cohort=()"
    
    # HSTS - Force HTTPS
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    
    # Content Security Policy
    Content-Security-Policy = '''
      default-src 'self' https:;
      script-src 'self' 'unsafe-inline' 'unsafe-eval' https://www.googletagmanager.com https://www.google-analytics.com https://www.googleadservices.com https://googleads.g.doubleclick.net https://www.google.com;
      style-src 'self' 'unsafe-inline' https://fonts.googleapis.com;
      style-src-elem 'self' 'unsafe-inline' https://fonts.googleapis.com;
      img-src 'self' data: https: blob: https://www.google.com https://www.googletagmanager.com;
      font-src 'self' data: https://fonts.gstatic.com;
      connect-src 'self' https://api.openweathermap.org https://www.google-analytics.com https://api.emailjs.com https://*.netlify.app/.netlify/functions/ https://www.google.com https://www.googleadservices.com https://googleads.g.doubleclick.net;
      frame-src 'self' https://td.doubleclick.net https://www.googletagmanager.com;
      frame-ancestors 'none';
      base-uri 'self';
      form-action 'self' https://formspree.io;
      upgrade-insecure-requests;
    '''

# Additional headers for static assets
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.webp"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"